services:
  node:
    build:
      context: .
      args:
        - build_number_ci
    command: npm run watch
    environment:
      APP_PORT: 17201
      VOO_MODEM_PASSWORD: ${VOO_MODEM_PASSWORD}
      VOO_MODEM_FECTH_INTERVAL: 60000
      OPEN_WEATHER_MAP_API_KEY: ${OPEN_WEATHER_MAP_API_KEY}
      OPEN_WEATHER_MAP_LOCATION_LAT: ${OPEN_WEATHER_MAP_LOCATION_LAT}
      OPEN_WEATHER_MAP_LOCATION_LON: ${OPEN_WEATHER_MAP_LOCATION_LON}
      WORKERS_ERROR_THROTTLING: 2000
      POSTGRES_DB: voo_stats
      POSTGRES_HOST: postgresql
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: postgres
      WORKERS_ON: 1
    ports:
      - '19201:17201'
    volumes:
      - ./config:/var/www/config
      - ./src:/var/www/src
      - ./package.json:/var/www/package.json
      - ./package-lock.json:/var/www/package-lock.json
    depends_on:
      - 'postgresql'
    links:
      - postgresql

  waithosts:
    image: blablalines/wait:2.6.0-slim
    environment:
      WAIT_HOSTS: postgresql:5432
    depends_on:
      - 'postgresql'
    links:
      - postgresql

  postgresql:
    image: postgres:14.2-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./bootstrap/postgresql:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '19432:5432'

volumes:
  pgdata:
